[package]
name = "kiwi"
version = "0.1.0"
edition = "2021"

[lib]
version = "0.1.0"
edition = "2021"
path = "src/lib/lib.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4"