@kiwiApi = {{protocol}}://{{hostname}}:{{port}}/api

@raceId = 637d9fc563342dd480dd4039
GET  {{kiwiApi}}/race.get?id={{raceId}}

###

GET {{kiwiApi}}/race.find

###

@raceName = Gfny
@raceCity = Villavicencio
GET {{kiwiApi}}/race.find
    ?name={{raceName}}
    &city={{raceCity}}

###

