@kiwiApi = {{protocol}}://{{hostname}}:{{port}}/api

@raceId = 637d9fc563342dd480dd4039
GET  {{kiwiApi}}/race.get?id={{raceId}}

###

GET {{kiwiApi}}/race.find

###

@raceName = Gfny
@raceCity = Villavicencio
GET {{kiwiApi}}/race.find
    ?name={{raceName}}
    &city={{raceCity}}

###

POST {{kiwiApi}}/race.create
Content-Type: application/json

{
    "name": "test",
    "distance": 1.2,
    "discipline": "Road",
    "date": "2023-12-16 16:40:36Z",
    "location": {
        "address": "Centro",
        "city": "Sopo",
        "state": "Cundinamarca",
        "country": "Colombia"
    },
    "image": "empty.png"
}