@startuml Domain

hide circle
hide empty members
skinparam linetype ortho
skinparam nodesep 200

class Customer {
  name:String
  nidType:String
  nid:String
  status:String
  createdAt:DateTime
  updatedAt:DateTime
}

class Risk {
  rating:String
  createdAt:DateTime
  updatedAt:DateTime
}

class Location {
    address:String
    city:String
    state:String
    detail:String
}

class Subscription {
    status:String
    createdAt:DateTime
    updatedAt:DateTime
}

class Contact {
  name:String
  nidType:String
  nid:String
  phone:String
  email:String
  jobTitle:String
  createdAt:DateTime
  updatedAt:DateTime
}

class ContactRegistry {
  priority:Integer
  createdAt:DateTime
  updatedAt:DateTime
}

class ProcessInstance {
  workflowId:String
  status:String
  cratedAt:DateTime
  updatedAt:DateTime
}

class StageInstance {
  status:String
  createdAt:DateTime
  updatedAt:DateTime
}

class Comment {
  text:String
  createdAt:DateTime
  updatedAt:DateTime
}

class File {
  name:String
  description:String
  path:String
  createdAt:DateTime
  updatedAt:DateTime
}

Product -- "*" Subscription:Has >

Customer -u- Location
Customer -l- "*" ProcessInstance
Customer -- Risk:Has >

ProcessInstance -- StageInstance:Has >

Comment -- "0..1" StageInstance:AssociatedWith >
Comment -l- "0..1" File:AssociatedWith >

StageInstance -- File:UploadedIn <

Subscription -- "+" ContactRegistry
Subscription "*" -- Customer:Has >

ContactRegistry "+" -- Contact

Process -- "*" ProcessInstance:AssociatedWith <

@enduml