@startuml Domain


hide circle
hide empty members
skinparam linetype ortho
skinparam nodesep 200

class Score {
  amount:Money
  status:String
  createdAt:DateTime
  updatedAt:DateTime
}

class Customer {
  name:String
  nidType:String
  nid:String
  status:String
  createdAt:DateTime
  updatedAt:DateTime
}

class Risk {
  rating:String
  createdAt:DateTime
  updatedAt:DateTime
}

class Location {
    address:String
    city:String
    state:String
}

class Product {
    name:String
    code:String
}

class Subscription {
    status:String
    createdAt:DateTime
}

class Country {
  name:String
  timeZone:String
}

class Contact {
  name:String
  nidType:String
  nid:String
  phone:String
  email:String
  jobTitle:String
  createdAt:DateTime
  updatedAt:DateTime
}

class ContactRegistry {
  priority:Integer
  createdAt:DateTime
}

class Process {
  name:String
  workflow:String
}

class Stage {
  name:String
}

class Instance {
  status:String
  cratedAt:DateTime
}

class Loan {
  capital:Money
  interest:Money
  taxes:Money
  platformCost:Money
  delinquentInterest:Money
  finalAmount:Money
  debtBalance:Money
  status:String
  takenAt:DateTime
  dueDate:DateTIme
  createdAt:DateTime
  updatedAt:DateTime
}

class Payment {
    type:String
    status:String
    paidAt:DateTime
    amount:Money
    capital:Money
    interest:Money
    taxes:Money
    platformCost:Money
    delinquentInterest:Money
    createdAt:DateTime
    updatedAt:DateTime
}

class Currency {
  name:String
  code:String
  symbol:String
}

class Exchange {
    rateFromUsd:Real
    createdAt:DateTime
    updatedAt:DateTime
}

class Agreement {
  name:String
  min:Money
  max:Money
}

class Clause {

}

class Rate {
  value:Rate
}

class Fee {
  amount:Money
}

class Charge {
  amount:Money
}

Country -- "*" Product:Has >
Country -l- "*" Currency:HasOfficial >

Product -- "*" Subscription:Has >
Product -- "+" Currency:HasAllowed >

Customer -r- Location
Customer -- "*" Instance
Customer -- Risk:Has >

Subscription -r- Score
Subscription -- "+" ContactRegistry
Subscription "*" -- Customer:Has >

ContactRegistry "+" -- Contact

Process -- Stage:Has >

Process --r-- "*" Instance:AssociatedWith <

Loan "*" -r- Subscription:BelongsTo >
Loan -- "*" Payment:Has >
Loan -- Currency:MadeOn >

Currency -- Exchange:ExchangedBy >

@enduml