[server]
port = "7878"
env = "Dev"

[log]
level = "info"

[db]
connection_string = "mongodb+srv://fredyd:beto8712@cluster0.ilsnrak.mongodb.net/?retryWrites=true&w=majority"
db_name = "kiwi"
races_collection = "races"